In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
import tensorflow as tf
import tensorflow_decision_forests as tfdf

In [51]:
train_df = pd.read_csv("/Users/aleksandr/Документы/TitanicML/data/train.csv")
test_df = pd.read_csv("/Users/aleksandr/Документы/TitanicML/data/test.csv")

train_df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [52]:
def preprocess(df):
    df = df.copy()
    def normaloize_name(x):
        return " ".join([v.strip(",()[].\"'") for v in x.split(" ")])
    def ticket_number(x):
        return x.split(" ")[-1]
    def ticket_item(x):
        items = x.split(" ")
        if len(items) == 1:
            return "None"
        return "_".join(items[0:-1])
    
    df["Name"] = df["Name"].apply(normaloize_name)
    df["Ticket_number"] = df["Ticket"].apply(ticket_number)
    df["Ticket_item"] = df["Ticket"].apply(ticket_item)
    return df

preprocess_train_df = preprocess(train_df)
preprocess_test_df = preprocess(test_df)

categorical_columns = preprocess_train_df.select_dtypes(
    include=["object", "category"]
).columns

for col in categorical_columns:
    preprocess_train_df[col] = (
        preprocess_train_df[col]
        .fillna("__MISSING__")
        .astype(str)
    )

    preprocess_test_df[col] = (
        preprocess_test_df[col]
        .fillna("__MISSING__")
        .astype(str)
    )

preprocess_train_df.head()

/var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/ipykernel_54728/632754599.py:21: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = preprocess_train_df.select_dtypes(

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Ticket_number,Ticket_item
0,1,0,3,Braund Mr Owen Harris,male,22.0,1,0,A/5 21171,7.2500,__MISSING__,S,21171,A/5
1,2,1,1,Cumings Mrs John Bradley Florence Briggs Thayer,female,38.0,1,0,PC 17599,71.2833,C85,C,17599,PC
2,3,1,3,Heikkinen Miss Laina,female,26.0,0,0,STON/O2. 3101282,7.9250,__MISSING__,S,3101282,STON/O2.
3,4,1,1,Futrelle Mrs Jacques Heath Lily May Peel,female,35.0,1,0,113803,53.1000,C123,S,113803,None
4,5,0,3,Allen Mr William Henry,male,35.0,0,0,373450,8.0500,__MISSING__,S,373450,None

In [53]:
input_features = list(preprocess_train_df.columns)
input_features.remove("Ticket")
input_features.remove("PassengerId")
input_features.remove("Survived")

print(f"Input features: {input_features}")

Input features: ['Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin', 'Embarked', 'Ticket_number', 'Ticket_item']

In [54]:
def tokenize_names(features, labels=None):
    features["Name"] =  tf.strings.split(features["Name"])
    return features, labels

train_ds = tfdf.keras.pd_dataframe_to_tf_dataset(preprocess_train_df,label="Survived").map(tokenize_names)
test_ds = tfdf.keras.pd_dataframe_to_tf_dataset(preprocess_test_df).map(tokenize_names)

In [55]:
model = tfdf.keras.GradientBoostedTreesModel(
    verbose=1, 
    features=[tfdf.keras.FeatureUsage(name=n) for n in input_features],
    exclude_non_specified_features=True,
    min_examples=1,
    categorical_algorithm="RANDOM",
    shrinkage=0.05,
    split_axis="SPARSE_OBLIQUE",
    sparse_oblique_normalization="MIN_MAX",
    sparse_oblique_num_projections_exponent=2.0,
    num_trees=2000,
    random_seed=1234,
    
)
model.fit(train_ds)

self_evaluation = model.make_inspector().evaluation()
print(f"Accuracy: {self_evaluation.accuracy} Loss:{self_evaluation.loss}")

Use /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpgz9aqwy8 as temporary training directory
Reading training dataset...
Training dataset read in 0:00:00.097715. Found 891 examples.
Training model...

[WARNING 26-10-01 21:12:12.5594 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:12.5595 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:12.5595 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

Model trained in 0:00:00.179060
Compiling model...
Model compiled.
Accuracy: 0.79347825050354 Loss:1.0656445026397705

[INFO 26-10-01 21:12:12.8410 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpgz9aqwy8/model/ with prefix c8fa76c76206481c
[INFO 26-10-01 21:12:12.8428 +06 decision_forest.cc:660] Model loaded with 34 root(s), 1818 node(s), and 11 input feature(s).
[INFO 26-10-01 21:12:12.8428 +06 abstract_model.cc:1344] Engine "GradientBoostedTreesGeneric" built
[INFO 26-10-01 21:12:12.8428 +06 kernel.cc:1061] Use fast generic engine

In [56]:
model.summary()

Model: "gradient_boosted_trees_model_311"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
=================================================================
Total params: 1 (1.00 Byte)
Trainable params: 0 (0.00 Byte)
Non-trainable params: 1 (1.00 Byte)
_________________________________________________________________
Type: "GRADIENT_BOOSTED_TREES"
Task: CLASSIFICATION
Label: "__LABEL"

Input Features (11):
	Age
	Cabin
	Embarked
	Fare
	Name
	Parch
	Pclass
	Sex
	SibSp
	Ticket_item
	Ticket_number

No weights

Variable Importance: INV_MEAN_MIN_DEPTH:
    1.           "Sex"  0.588943 ################
    2.           "Age"  0.346745 ######
    3.          "Fare"  0.269876 ###
    4.          "Name"  0.205647 #
    5.         "Cabin"  0.185368
    6.        "Pclass"  0.181872
    7. "Ticket_number"  0.180223
    8.   "Ticket_item"  0.175626
    9.         "Parch"  0.174643
   10.      "Embarked"  0.173688
   11.         "SibSp"  0.171216

Variable Importance: NUM_AS_ROOT:
    1.  "Sex" 29.000000 ################
    2. "Name"  5.000000

Variable Importance: NUM_NODES:
    1.           "Age" 427.000000 ################
    2.          "Fare" 270.000000 ##########
    3.          "Name" 52.000000 #
    4.   "Ticket_item" 34.000000 #
    5.           "Sex" 32.000000 #
    6. "Ticket_number" 22.000000
    7.         "Parch" 17.000000
    8.         "Cabin" 16.000000
    9.        "Pclass" 12.000000
   10.      "Embarked"  5.000000
   11.         "SibSp"  5.000000

Variable Importance: SUM_SCORE:
    1.           "Sex" 429.991580 ################
    2.           "Age" 352.245788 #############
    3.          "Fare" 268.630905 #########
    4.          "Name" 153.238593 #####
    5.        "Pclass" 45.842595 #
    6.         "Cabin" 24.215736
    7. "Ticket_number" 22.497265
    8.   "Ticket_item" 18.571183
    9.         "Parch"  8.449955
   10.      "Embarked"  4.721665
   11.         "SibSp"  0.037139



Loss: BINOMIAL_LOG_LIKELIHOOD
Validation loss value: 1.06564
Number of trees per iteration: 1
Node format: NOT_SET
Number of trees: 34
Total number of nodes: 1818

Number of nodes by tree:
Count: 34 Average: 53.4706 StdDev: 5.51061
Min: 39 Max: 61 Ignored: 0
----------------------------------------------
[ 39, 40) 2   5.88%   5.88% ###
[ 40, 41) 0   0.00%   5.88%
[ 41, 42) 0   0.00%   5.88%
[ 42, 43) 0   0.00%   5.88%
[ 43, 44) 0   0.00%   5.88%
[ 44, 45) 0   0.00%   5.88%
[ 45, 47) 1   2.94%   8.82% #
[ 47, 48) 3   8.82%  17.65% ####
[ 48, 49) 0   0.00%  17.65%
[ 49, 50) 1   2.94%  20.59% #
[ 50, 51) 0   0.00%  20.59%
[ 51, 52) 5  14.71%  35.29% #######
[ 52, 53) 0   0.00%  35.29%
[ 53, 55) 3   8.82%  44.12% ####
[ 55, 56) 5  14.71%  58.82% #######
[ 56, 57) 0   0.00%  58.82%
[ 57, 58) 7  20.59%  79.41% ##########
[ 58, 59) 0   0.00%  79.41%
[ 59, 60) 5  14.71%  94.12% #######
[ 60, 61] 2   5.88% 100.00% ###

Depth by leafs:
Count: 926 Average: 4.85961 StdDev: 0.430668
Min: 2 Max: 5 Ignored: 0
----------------------------------------------
[ 2, 3)   2   0.22%   0.22%
[ 3, 4)  24   2.59%   2.81%
[ 4, 5)  76   8.21%  11.02% #
[ 5, 5] 824  88.98% 100.00% ##########

Number of training obs by leaf:
Count: 926 Average: 29.3369 StdDev: 75.2668
Min: 1 Max: 474 Ignored: 0
----------------------------------------------
[   1,  24) 734  79.27%  79.27% ##########
[  24,  48)  76   8.21%  87.47% #
[  48,  72)  33   3.56%  91.04%
[  72,  95)   8   0.86%  91.90%
[  95, 119)   9   0.97%  92.87%
[ 119, 143)   7   0.76%  93.63%
[ 143, 166)  17   1.84%  95.46%
[ 166, 190)   6   0.65%  96.11%
[ 190, 214)   3   0.32%  96.44%
[ 214, 238)   1   0.11%  96.54%
[ 238, 261)   1   0.11%  96.65%
[ 261, 285)   2   0.22%  96.87%
[ 285, 309)   0   0.00%  96.87%
[ 309, 332)   0   0.00%  96.87%
[ 332, 356)   4   0.43%  97.30%
[ 356, 380)   5   0.54%  97.84%
[ 380, 403)   8   0.86%  98.70%
[ 403, 427)   9   0.97%  99.68%
[ 427, 451)   1   0.11%  99.78%
[ 451, 474]   2   0.22% 100.00%

Attribute in nodes:
	427 : Age [NUMERICAL]
	270 : Fare [NUMERICAL]
	52 : Name [CATEGORICAL_SET]
	34 : Ticket_item [CATEGORICAL]
	32 : Sex [CATEGORICAL]
	22 : Ticket_number [CATEGORICAL]
	17 : Parch [NUMERICAL]
	16 : Cabin [CATEGORICAL]
	12 : Pclass [NUMERICAL]
	5 : SibSp [NUMERICAL]
	5 : Embarked [CATEGORICAL]

Attribute in nodes with depth <= 0:
	29 : Sex [CATEGORICAL]
	5 : Name [CATEGORICAL_SET]

Attribute in nodes with depth <= 1:
	34 : Age [NUMERICAL]
	29 : Sex [CATEGORICAL]
	22 : Fare [NUMERICAL]
	6 : Pclass [NUMERICAL]
	5 : Name [CATEGORICAL_SET]
	5 : Cabin [CATEGORICAL]
	1 : Ticket_number [CATEGORICAL]

Attribute in nodes with depth <= 2:
	105 : Age [NUMERICAL]
	60 : Fare [NUMERICAL]
	30 : Sex [CATEGORICAL]
	13 : Name [CATEGORICAL_SET]
	9 : Cabin [CATEGORICAL]
	7 : Ticket_number [CATEGORICAL]
	6 : Pclass [NUMERICAL]
	3 : Embarked [CATEGORICAL]
	2 : Parch [NUMERICAL]
	1 : Ticket_item [CATEGORICAL]

Attribute in nodes with depth <= 3:
	213 : Age [NUMERICAL]
	139 : Fare [NUMERICAL]
	30 : Sex [CATEGORICAL]
	28 : Name [CATEGORICAL_SET]
	19 : Ticket_number [CATEGORICAL]
	14 : Ticket_item [CATEGORICAL]
	12 : Parch [NUMERICAL]
	12 : Cabin [CATEGORICAL]
	8 : Pclass [NUMERICAL]
	5 : Embarked [CATEGORICAL]

Attribute in nodes with depth <= 5:
	427 : Age [NUMERICAL]
	270 : Fare [NUMERICAL]
	52 : Name [CATEGORICAL_SET]
	34 : Ticket_item [CATEGORICAL]
	32 : Sex [CATEGORICAL]
	22 : Ticket_number [CATEGORICAL]
	17 : Parch [NUMERICAL]
	16 : Cabin [CATEGORICAL]
	12 : Pclass [NUMERICAL]
	5 : SibSp [NUMERICAL]
	5 : Embarked [CATEGORICAL]

Condition type in nodes:
	731 : ObliqueCondition
	126 : ContainsBitmapCondition
	35 : ContainsCondition
Condition type in nodes with depth <= 0:
	34 : ContainsBitmapCondition
Condition type in nodes with depth <= 1:
	62 : ObliqueCondition
	40 : ContainsBitmapCondition
Condition type in nodes with depth <= 2:
	173 : ObliqueCondition
	60 : ContainsBitmapCondition
	3 : ContainsCondition
Condition type in nodes with depth <= 3:
	372 : ObliqueCondition
	93 : ContainsBitmapCondition
	15 : ContainsCondition
Condition type in nodes with depth <= 5:
	731 : ObliqueCondition
	126 : ContainsBitmapCondition
	35 : ContainsCondition

Training logs:
Number of iteration to final model: 34
	Iter:1 train-loss:1.266910 valid-loss:1.364115  train-accuracy:0.624531 valid-accuracy:0.543478
	Iter:2 train-loss:1.215680 valid-loss:1.335395  train-accuracy:0.624531 valid-accuracy:0.543478
	Iter:3 train-loss:1.168280 valid-loss:1.305821  train-accuracy:0.624531 valid-accuracy:0.543478
	Iter:4 train-loss:1.120181 valid-loss:1.274103  train-accuracy:0.624531 valid-accuracy:0.543478
	Iter:5 train-loss:1.079277 valid-loss:1.247148  train-accuracy:0.792240 valid-accuracy:0.706522
	Iter:6 train-loss:1.043451 valid-loss:1.225859  train-accuracy:0.822278 valid-accuracy:0.706522
	Iter:16 train-loss:0.789545 valid-loss:1.118144  train-accuracy:0.909887 valid-accuracy:0.750000
	Iter:26 train-loss:0.651334 valid-loss:1.073267  train-accuracy:0.919900 valid-accuracy:0.782609
	Iter:36 train-loss:0.558133 valid-loss:1.065861  train-accuracy:0.931164 valid-accuracy:0.782609
	Iter:46 train-loss:0.495355 valid-loss:1.076354  train-accuracy:0.937422 valid-accuracy:0.771739
	Iter:56 train-loss:0.451245 valid-loss:1.089698  train-accuracy:0.948686 valid-accuracy:0.728261

In [ ]:

def prediction(model, test_df, passenger_ids, threshold=0.5):    
    proba_survive = model.predict(test_ds, verbose=0)[:, 0]
    
    return pd.DataFrame({
        "PassengerId": passenger_ids,
        "Survived": (proba_survive >= threshold).astype(int)
    })

k_prediction = prediction(model, test_ds, test_df["PassengerId"])

def make_submission(k_prediction):
    path = "/Users/aleksandr/Документы/TitanicML/data/gender_submission.csv"
    k_prediction.to_csv(path, index=False)
    print(f"Submission exported to {path}")

make_submission(k_prediction)

Submission exported to /Users/aleksandr/Документы/TitanicML/data/gender_submission.csv

In [ ]:
tuner = tfdf.tuner.RandomSearch(num_trials=1000)
tuner.choice("min_examples", [2, 5, 7, 10])
tuner.choice("categorical_algorithm", ["CART", "RANDOM"])

local_search_space = tuner.choice("growing_strategy", ["LOCAL"])
local_search_space.choice("max_depth", [3, 4, 5, 6, 8])

global_search_space = tuner.choice("growing_strategy", ["BEST_FIRST_GLOBAL"], merge=True)
global_search_space.choice("max_num_nodes", [16, 32, 64, 128, 256])

tuner.choice("shrinkage", [0.02, 0.05, 0.10, 0.15])
tuner.choice("num_candidate_attributes_ratio", [0.2, 0.5, 0.9, 1.0])


tuner.choice("split_axis", ["AXIS_ALIGNED"])
oblique_space = tuner.choice("split_axis", ["SPARSE_OBLIQUE"], merge=True)
oblique_space.choice("sparse_oblique_normalization",
                     ["NONE", "STANDARD_DEVIATION", "MIN_MAX"])
oblique_space.choice("sparse_oblique_weights", ["BINARY", "CONTINUOUS"])
oblique_space.choice("sparse_oblique_num_projections_exponent", [1.0, 1.5])

tuned_model = tfdf.keras.GradientBoostedTreesModel(tuner=tuner)
tuned_model.fit(train_ds, verbose=0)

tuned_self_evaluation = tuned_model.make_inspector().evaluation()
print(f"Accuracy: {tuned_self_evaluation.accuracy} Loss:{tuned_self_evaluation.loss}")

Use /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpms6sr_at as temporary training directory

[WARNING 26-10-01 21:12:12.9665 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:12.9665 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:12.9665 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

Accuracy: 0.8493150472640991 Loss:0.6777517199516296

[INFO 26-10-01 21:12:29.8705 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpms6sr_at/model/ with prefix ef25c5d279e14c52
[INFO 26-10-01 21:12:29.8845 +06 decision_forest.cc:660] Model loaded with 84 root(s), 10236 node(s), and 13 input feature(s).
[INFO 26-10-01 21:12:29.8845 +06 abstract_model.cc:1344] Engine "GradientBoostedTreesGeneric" built
[INFO 26-10-01 21:12:29.8845 +06 kernel.cc:1061] Use fast generic engine

In [ ]:
predictions = None
num_predictions = 0

for i in range(100):
    print(f"i:{i}")
    model = tfdf.keras.GradientBoostedTreesModel(
        verbose=0, # Very few logs
        features=[tfdf.keras.FeatureUsage(name=n) for n in input_features],
        exclude_non_specified_features=True, 
        random_seed=i,
        honest=True,
    )
    model.fit(train_ds)
    
    sub_predictions = model.predict(test_ds, verbose=0)[:,0]
    if predictions is None:
        predictions = sub_predictions
    else:
        predictions += sub_predictions
    num_predictions += 1

predictions/=num_predictions

kaggle_predictions = pd.DataFrame({
        "PassengerId": test_df["PassengerId"],
        "Survived": (predictions >= 0.5).astype(int)
    })

make_submission(kaggle_predictions)

[WARNING 26-10-01 21:12:29.9604 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:29.9604 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:29.9604 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:0

[INFO 26-10-01 21:12:30.1338 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpi6b4xk5m/model/ with prefix 67ff310e140649d1
[INFO 26-10-01 21:12:30.1351 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:30.2242 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:30.2242 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:30.2242 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:1

[INFO 26-10-01 21:12:30.4005 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpz8437_yn/model/ with prefix 558c82f3f357417b
[INFO 26-10-01 21:12:30.4020 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:30.4922 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:30.4923 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:30.4923 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:2

[INFO 26-10-01 21:12:30.6720 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpskx8gwcj/model/ with prefix 9ac5e11fd96e4c03
[INFO 26-10-01 21:12:30.6737 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:30.7608 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:30.7609 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:30.7609 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:3

[INFO 26-10-01 21:12:30.9562 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp2rjm54av/model/ with prefix 057aa000c6ff4de0
[INFO 26-10-01 21:12:30.9584 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:31.0447 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:31.0447 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:31.0447 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:4

[INFO 26-10-01 21:12:31.2106 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp553bs40p/model/ with prefix 9aa8c49f20f54ba7
[INFO 26-10-01 21:12:31.2119 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:31.2992 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:31.2992 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:31.2992 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:5

[INFO 26-10-01 21:12:31.4521 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmphl974ox6/model/ with prefix 98dd0c722c7241ad
[INFO 26-10-01 21:12:31.4530 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:31.5389 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:31.5390 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:31.5390 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:6

[INFO 26-10-01 21:12:31.7883 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp4mxgfcqb/model/ with prefix abf17dc081f04605
[INFO 26-10-01 21:12:31.7917 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:31.8778 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:31.8778 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:31.8778 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:7

[INFO 26-10-01 21:12:32.0401 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp539iobhm/model/ with prefix 94df6593b8dc4f7b
[INFO 26-10-01 21:12:32.0413 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:32.1284 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:32.1284 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:32.1284 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:8

[INFO 26-10-01 21:12:32.3267 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp7mccf9mm/model/ with prefix ca05245e6c454db3
[INFO 26-10-01 21:12:32.3288 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:32.4149 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:32.4150 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:32.4150 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:9

[INFO 26-10-01 21:12:32.5882 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmptvc0k58m/model/ with prefix 118bec503f3d4593
[INFO 26-10-01 21:12:32.5897 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:32.6750 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:32.6750 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:32.6750 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:10

[INFO 26-10-01 21:12:32.8830 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpgbo7tq3l/model/ with prefix b59c9f75516e434b
[INFO 26-10-01 21:12:32.8855 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:32.9736 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:32.9736 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:32.9736 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:11

[INFO 26-10-01 21:12:33.2206 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp_xoi4r8r/model/ with prefix 91f8528978a44a96
[INFO 26-10-01 21:12:33.2238 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:33.3085 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:33.3085 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:33.3086 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:12

[INFO 26-10-01 21:12:33.4752 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp72ihs4a_/model/ with prefix 10b6e6942acb4702
[INFO 26-10-01 21:12:33.4765 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:33.5634 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:33.5634 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:33.5634 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:13

[INFO 26-10-01 21:12:33.7886 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpx0uc_e_l/model/ with prefix e3769b9fef0d4c6a
[INFO 26-10-01 21:12:33.7912 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:33.8782 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:33.8783 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:33.8783 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:14

[INFO 26-10-01 21:12:34.0742 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmph_hmrv9p/model/ with prefix cc4d91be57d6422a
[INFO 26-10-01 21:12:34.0764 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:34.1626 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:34.1626 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:34.1626 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:15

[INFO 26-10-01 21:12:34.3291 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp8n5mfn4f/model/ with prefix b175ee155c02479f
[INFO 26-10-01 21:12:34.3305 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:34.4232 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:34.4232 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:34.4232 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:16

[INFO 26-10-01 21:12:34.6060 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpbffli_tu/model/ with prefix 5e80efdc750a4e97
[INFO 26-10-01 21:12:34.6076 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:34.6946 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:34.6946 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:34.6947 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:17

[INFO 26-10-01 21:12:34.9343 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmphd_n_t4j/model/ with prefix 059830dda558462c
[INFO 26-10-01 21:12:34.9384 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:35.0748 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:35.0749 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:35.0749 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:18

[INFO 26-10-01 21:12:35.2677 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp633i9iug/model/ with prefix 1afaa84fff29487a
[INFO 26-10-01 21:12:35.2694 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:35.3639 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:35.3639 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:35.3639 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:19

[INFO 26-10-01 21:12:35.6573 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpyjoaym8c/model/ with prefix bc78a603f75f48ed
[INFO 26-10-01 21:12:35.6609 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:35.7606 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:35.7606 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:35.7606 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:20

[INFO 26-10-01 21:12:36.0022 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpl7b19kk3/model/ with prefix 74bea0c618ed4a6a
[INFO 26-10-01 21:12:36.0050 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:36.0935 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:36.0935 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:36.0935 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:21

[INFO 26-10-01 21:12:36.2940 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpqhl1j8g1/model/ with prefix 947ac46f80294062
[INFO 26-10-01 21:12:36.2961 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:36.3828 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:36.3828 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:36.3828 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:22

[INFO 26-10-01 21:12:36.5798 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpouyj0rym/model/ with prefix aa61bb34fb61416b
[INFO 26-10-01 21:12:36.5818 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:36.6666 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:36.6666 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:36.6666 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:23

[INFO 26-10-01 21:12:36.8902 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpngfvn6ss/model/ with prefix c8158f65039f4bb4
[INFO 26-10-01 21:12:36.8925 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:36.9928 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:36.9928 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:36.9928 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:24

[INFO 26-10-01 21:12:37.1679 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpnqsocf_c/model/ with prefix 3108422f716a4c1a
[INFO 26-10-01 21:12:37.1694 +06 kernel.cc:1061] Use fast generic engine

i:25

[WARNING 26-10-01 21:12:37.6532 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:37.6532 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:37.6532 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
[INFO 26-10-01 21:12:37.8583 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpvab2s2u1/model/ with prefix f91b1ff1af634662
[INFO 26-10-01 21:12:37.8606 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:37.9556 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:37.9556 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:37.9556 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:26

[INFO 26-10-01 21:12:38.1749 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpj6p7tem3/model/ with prefix 6917a2e85e774b32
[INFO 26-10-01 21:12:38.1777 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:38.2781 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:38.2781 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:38.2781 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:27

[INFO 26-10-01 21:12:38.5150 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpc7cag5ss/model/ with prefix dc86a70fa3ca4746
[INFO 26-10-01 21:12:38.5182 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:38.6155 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:38.6156 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:38.6156 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:28

[INFO 26-10-01 21:12:38.7859 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmps3w47tl_/model/ with prefix c768c4e1fba04159
[INFO 26-10-01 21:12:38.7871 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:38.8814 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:38.8814 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:38.8814 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:29

[INFO 26-10-01 21:12:39.0621 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpsurhq2bz/model/ with prefix c43d16ba89c24535
[INFO 26-10-01 21:12:39.0636 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:39.1592 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:39.1592 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:39.1592 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:30

[INFO 26-10-01 21:12:39.3983 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpl3ogwkzn/model/ with prefix af29b684bf3b4342
[INFO 26-10-01 21:12:39.4016 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:39.4946 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:39.4946 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:39.4946 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:31

[INFO 26-10-01 21:12:39.7712 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp0v47snse/model/ with prefix 20e2bf59fb1245e4
[INFO 26-10-01 21:12:39.7748 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:39.8618 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:39.8618 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:39.8618 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:32

[INFO 26-10-01 21:12:40.0702 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp174832x1/model/ with prefix e1439f089b4e4f08
[INFO 26-10-01 21:12:40.0727 +06 abstract_model.cc:1344] Engine "GradientBoostedTreesQuickScorerExtended" built
[INFO 26-10-01 21:12:40.0727 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:40.1621 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:40.1621 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:40.1621 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:33

[INFO 26-10-01 21:12:40.3649 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpa5w7jndp/model/ with prefix 1838155506684f29
[INFO 26-10-01 21:12:40.3669 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:40.4557 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:40.4557 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:40.4557 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:34

[INFO 26-10-01 21:12:40.6350 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp5j1kub2s/model/ with prefix a0de599b151e40b6
[INFO 26-10-01 21:12:40.6366 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:40.7264 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:40.7264 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:40.7264 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:35

[INFO 26-10-01 21:12:40.9274 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp39y8hhdl/model/ with prefix e8e48943a6054463
[INFO 26-10-01 21:12:40.9297 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:41.0166 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:41.0166 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:41.0166 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:36

[INFO 26-10-01 21:12:41.1815 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpddui11sh/model/ with prefix 5281290c0e524ab5
[INFO 26-10-01 21:12:41.1827 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:41.2699 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:41.2699 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:41.2699 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:37

[INFO 26-10-01 21:12:41.4891 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpn_n5892e/model/ with prefix 2141ca3f6d4f4fd2
[INFO 26-10-01 21:12:41.4917 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:41.5809 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:41.5809 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:41.5809 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:38

[INFO 26-10-01 21:12:41.9798 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpeanwsv49/model/ with prefix 887e8109546d4d0b
[INFO 26-10-01 21:12:41.9868 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:42.0761 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:42.0761 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:42.0761 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:39

[INFO 26-10-01 21:12:42.3414 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpgtgswxp1/model/ with prefix 176d2d0cb36d4f11
[INFO 26-10-01 21:12:42.3452 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:42.4337 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:42.4337 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:42.4337 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:40

[INFO 26-10-01 21:12:42.6610 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmps8gg3t7s/model/ with prefix d05593199fcb4bc1
[INFO 26-10-01 21:12:42.6633 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:42.7661 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:42.7662 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:42.7662 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:41

[INFO 26-10-01 21:12:42.9840 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpbi5loo37/model/ with prefix b24d30acf5e84fc5
[INFO 26-10-01 21:12:42.9865 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:43.0753 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:43.0754 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:43.0754 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:42

[INFO 26-10-01 21:12:43.2374 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpt0prybpu/model/ with prefix 82e8db1e21e24860
[INFO 26-10-01 21:12:43.2384 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:43.3293 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:43.3293 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:43.3293 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:43

[INFO 26-10-01 21:12:43.6031 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpc6bc8nh9/model/ with prefix 442966a7c93d46af
[INFO 26-10-01 21:12:43.6068 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:43.6930 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:43.6930 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:43.6930 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:44

[INFO 26-10-01 21:12:43.8513 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp2seoq4df/model/ with prefix d06670b9d59640ee
[INFO 26-10-01 21:12:43.8523 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:43.9388 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:43.9389 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:43.9389 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:45

[INFO 26-10-01 21:12:44.1040 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp73nu3zbx/model/ with prefix 4c07ad6d0d5844c8
[INFO 26-10-01 21:12:44.1053 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:44.2223 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:44.2223 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:44.2224 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:46

[INFO 26-10-01 21:12:44.4095 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp2ayybyme/model/ with prefix f304e64d1dea427e
[INFO 26-10-01 21:12:44.4111 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:44.5065 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:44.5065 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:44.5065 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:47

[INFO 26-10-01 21:12:44.7841 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp0s6hxs5b/model/ with prefix 21e53d0ef1324b9c
[INFO 26-10-01 21:12:44.7876 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:44.8713 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:44.8713 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:44.8713 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:48

[INFO 26-10-01 21:12:45.0314 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpa_l_ydzf/model/ with prefix f377303c8d9e41ed
[INFO 26-10-01 21:12:45.0324 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:45.1185 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:45.1185 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:45.1185 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:49

[INFO 26-10-01 21:12:45.3388 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp920k208u/model/ with prefix 2516335fc5b6431f
[INFO 26-10-01 21:12:45.3412 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:45.4242 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:45.4242 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:45.4242 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:50

[INFO 26-10-01 21:12:45.6869 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp46xzgkn3/model/ with prefix 7912017becc44ec4
[INFO 26-10-01 21:12:45.6902 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:45.7745 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:45.7745 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:45.7746 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:51

[INFO 26-10-01 21:12:46.0050 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpvel_55x1/model/ with prefix 622572d976fd4f30
[INFO 26-10-01 21:12:46.0078 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:46.0921 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:46.0921 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:46.0921 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:52

[INFO 26-10-01 21:12:46.2702 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp7nxfcuyx/model/ with prefix 5f00f852c7744edf
[INFO 26-10-01 21:12:46.2717 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:46.3581 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:46.3581 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:46.3581 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:53

[INFO 26-10-01 21:12:46.5621 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpabg7emfv/model/ with prefix 4a57d4aa67674af6
[INFO 26-10-01 21:12:46.5641 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:46.6477 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:46.6477 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:46.6477 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:54

[INFO 26-10-01 21:12:46.8055 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpv3na98rc/model/ with prefix 7b551b5a14e244b3
[INFO 26-10-01 21:12:46.8065 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:46.8910 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:46.8910 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:46.8910 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:55

[INFO 26-10-01 21:12:47.0836 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmphpsmw3t7/model/ with prefix b1bb5eff53ec438a
[INFO 26-10-01 21:12:47.0854 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:47.1703 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:47.1703 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:47.1703 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:56

[INFO 26-10-01 21:12:47.4243 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmprquo5irw/model/ with prefix a6af2798df864cd5
[INFO 26-10-01 21:12:47.4276 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:47.5110 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:47.5111 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:47.5111 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:57

[INFO 26-10-01 21:12:47.7290 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp4elsxkt8/model/ with prefix 64c3176dca294f81
[INFO 26-10-01 21:12:47.7311 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:47.8155 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:47.8155 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:47.8155 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:58

[INFO 26-10-01 21:12:48.0561 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp6cngcgw7/model/ with prefix 4391c3bbe107453e
[INFO 26-10-01 21:12:48.0589 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:48.1437 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:48.1438 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:48.1438 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:59

[INFO 26-10-01 21:12:48.4265 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpl8xt2_bh/model/ with prefix 046de80d9a5c4602
[INFO 26-10-01 21:12:48.4303 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:48.5141 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:48.5141 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:48.5141 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:60

[INFO 26-10-01 21:12:48.7226 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp3mk_a9x9/model/ with prefix 0360a04ba3ea43e7
[INFO 26-10-01 21:12:48.7243 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:48.8119 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:48.8119 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:48.8119 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:61

[INFO 26-10-01 21:12:49.0165 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpihy6_0hb/model/ with prefix b70ab3ba11034ffb
[INFO 26-10-01 21:12:49.0185 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:49.1033 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:49.1033 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:49.1033 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:62

[INFO 26-10-01 21:12:49.3082 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpbz2rec24/model/ with prefix 0416294a525749e2
[INFO 26-10-01 21:12:49.3106 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:49.3956 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:49.3956 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:49.3956 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:63

[INFO 26-10-01 21:12:49.5589 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp1bw5u_em/model/ with prefix e0b0c648b64f4b13
[INFO 26-10-01 21:12:49.5599 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:49.6455 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:49.6455 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:49.6455 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:64

[INFO 26-10-01 21:12:49.8348 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpfuu9o31m/model/ with prefix 68d21212e32c442b
[INFO 26-10-01 21:12:49.8365 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:49.9237 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:49.9237 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:49.9237 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:65

[INFO 26-10-01 21:12:50.1041 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp9k_engd9/model/ with prefix 00732ff613ff4c74
[INFO 26-10-01 21:12:50.1056 +06 abstract_model.cc:1344] Engine "GradientBoostedTreesQuickScorerExtended" built
[INFO 26-10-01 21:12:50.1056 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:50.1934 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:50.1935 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:50.1935 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:66

[INFO 26-10-01 21:12:50.3724 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpp4qp44jx/model/ with prefix ab033432f8be438a
[INFO 26-10-01 21:12:50.3739 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:50.4578 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:50.4579 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:50.4579 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:67

[INFO 26-10-01 21:12:50.7000 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp4tjrx__b/model/ with prefix 5fbf84cb8bd8419d
[INFO 26-10-01 21:12:50.7027 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:50.7860 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:50.7860 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:50.7860 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:68

[INFO 26-10-01 21:12:51.0156 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmppl3bky0o/model/ with prefix 0f9a44b49ca04450
[INFO 26-10-01 21:12:51.0182 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:51.1026 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:51.1026 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:51.1026 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:69

[INFO 26-10-01 21:12:51.2788 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp2d7rusa5/model/ with prefix 31c0155e4f2b40ce
[INFO 26-10-01 21:12:51.2801 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:51.3653 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:51.3653 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:51.3653 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:70

[INFO 26-10-01 21:12:51.6369 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmppwrk1bv9/model/ with prefix 8d819c378a67406f
[INFO 26-10-01 21:12:51.6404 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:51.7257 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:51.7257 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:51.7257 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:71

[INFO 26-10-01 21:12:51.9248 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpgg0hdvnx/model/ with prefix fc8a35c276614b56
[INFO 26-10-01 21:12:51.9266 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:52.0193 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:52.0193 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:52.0193 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:72

[INFO 26-10-01 21:12:52.2341 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpp12wr5he/model/ with prefix 4b5b23903da0475d
[INFO 26-10-01 21:12:52.2364 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:52.3199 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:52.3200 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:52.3200 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:73

[INFO 26-10-01 21:12:52.5044 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp3ho_ncee/model/ with prefix efe19f1c75c34c12
[INFO 26-10-01 21:12:52.5059 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:52.5900 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:52.5901 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:52.5901 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:74

[INFO 26-10-01 21:12:52.9464 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp7afses0l/model/ with prefix cacbd61567d440c5
[INFO 26-10-01 21:12:52.9515 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:53.0374 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:53.0374 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:53.0374 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:75

[INFO 26-10-01 21:12:53.2857 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpdv4ll_ys/model/ with prefix 81bf8bf1b4c94356
[INFO 26-10-01 21:12:53.2886 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:53.3726 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:53.3726 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:53.3726 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:76

[INFO 26-10-01 21:12:53.5380 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpwltsvrq5/model/ with prefix 7569f27714624e79
[INFO 26-10-01 21:12:53.5390 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:53.6233 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:53.6233 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:53.6233 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:77

[INFO 26-10-01 21:12:54.1535 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp7j8aaejd/model/ with prefix 1e9697e3bbd94da5
[INFO 26-10-01 21:12:54.1550 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:54.2413 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:54.2413 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:54.2413 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:78

[INFO 26-10-01 21:12:54.4668 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp0jfkl_ic/model/ with prefix 0f4cada3404d4d3c
[INFO 26-10-01 21:12:54.4694 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:54.5557 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:54.5558 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:54.5558 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:79

[INFO 26-10-01 21:12:54.7649 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp2llk02de/model/ with prefix 71e0d829bfe94c1e
[INFO 26-10-01 21:12:54.7671 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:54.8541 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:54.8541 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:54.8541 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:80

[INFO 26-10-01 21:12:55.0217 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp7evnsgbe/model/ with prefix 2edbb08762594fc8
[INFO 26-10-01 21:12:55.0229 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:55.1104 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:55.1104 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:55.1105 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:81

[INFO 26-10-01 21:12:55.2916 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmplh11oqok/model/ with prefix 5e643a6529704406
[INFO 26-10-01 21:12:55.2930 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:55.3807 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:55.3807 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:55.3807 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:82

[INFO 26-10-01 21:12:55.5755 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpomvlbi7h/model/ with prefix 57473bd098bc46c7
[INFO 26-10-01 21:12:55.5773 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:55.6645 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:55.6645 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:55.6645 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:83

[INFO 26-10-01 21:12:55.8538 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpbp0or542/model/ with prefix 0c171255655840c4
[INFO 26-10-01 21:12:55.8555 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:55.9444 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:55.9444 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:55.9444 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:84

[INFO 26-10-01 21:12:56.1846 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpyczjj_rb/model/ with prefix 710a990f90364f6c
[INFO 26-10-01 21:12:56.1878 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:56.2748 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:56.2748 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:56.2748 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:85

[INFO 26-10-01 21:12:56.4372 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpm8if_r55/model/ with prefix a949ecad7d8f48ea
[INFO 26-10-01 21:12:56.4382 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:56.5244 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:56.5245 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:56.5245 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:86

[INFO 26-10-01 21:12:56.8195 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp8t27rr6m/model/ with prefix ea5f23f3d98d4e07
[INFO 26-10-01 21:12:56.8236 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:56.9087 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:56.9087 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:56.9087 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:87

[INFO 26-10-01 21:12:57.1464 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp6z5y2w0m/model/ with prefix cf7daa399c0b437a
[INFO 26-10-01 21:12:57.1493 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:57.2370 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:57.2370 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:57.2370 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:88

[INFO 26-10-01 21:12:57.4636 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpnjgz3dn8/model/ with prefix 9a733de05bcf40e0
[INFO 26-10-01 21:12:57.4658 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:57.5522 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:57.5522 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:57.5522 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:89

[INFO 26-10-01 21:12:57.7585 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp_infwgar/model/ with prefix 8b9be5f83868465e
[INFO 26-10-01 21:12:57.7607 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:57.8487 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:57.8487 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:57.8487 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:90

[INFO 26-10-01 21:12:58.0843 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpfu_nw8wx/model/ with prefix e3bc44a8925e4a2a
[INFO 26-10-01 21:12:58.0870 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:58.1728 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:58.1729 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:58.1729 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:91

[INFO 26-10-01 21:12:58.4156 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpf7ew29eg/model/ with prefix 6328f8d1f32f46de
[INFO 26-10-01 21:12:58.4184 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:58.5042 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:58.5042 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:58.5042 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:92

[INFO 26-10-01 21:12:58.7530 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpkhm5gv2_/model/ with prefix 4ba68d9f8cfc4f1c
[INFO 26-10-01 21:12:58.7561 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:58.8425 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:58.8425 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:58.8425 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:93

[INFO 26-10-01 21:12:59.0975 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmppc4xq3ri/model/ with prefix 310c2484ae2246cf
[INFO 26-10-01 21:12:59.1008 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:59.1881 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:59.1881 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:59.1881 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:94

[INFO 26-10-01 21:12:59.3726 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp9ging2ex/model/ with prefix 8e74a5d9cb744329
[INFO 26-10-01 21:12:59.3742 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:59.4616 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:59.4616 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:59.4616 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:95

[INFO 26-10-01 21:12:59.6297 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp2663vyt2/model/ with prefix e752f3b8853b4716
[INFO 26-10-01 21:12:59.6308 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:12:59.7180 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:59.7180 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:12:59.7180 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:96

[INFO 26-10-01 21:12:59.9347 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpasr9w487/model/ with prefix 1153e64154b74db8
[INFO 26-10-01 21:12:59.9372 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:13:00.0222 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:13:00.0222 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:13:00.0222 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:97

[INFO 26-10-01 21:13:00.2465 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpobvrlp2a/model/ with prefix d8b287cabbc94a81
[INFO 26-10-01 21:13:00.2486 +06 abstract_model.cc:1344] Engine "GradientBoostedTreesQuickScorerExtended" built
[INFO 26-10-01 21:13:00.2487 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:13:00.3327 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:13:00.3327 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:13:00.3328 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:98

[INFO 26-10-01 21:13:00.5563 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpxxvrwzzh/model/ with prefix 263d0e999beb4424
[INFO 26-10-01 21:13:00.5587 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 21:13:00.6433 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:13:00.6434 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 21:13:00.6434 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:99
Submission exported to /Users/aleksandr/Документы/TitanicML/data/gender_submission.csv

[INFO 26-10-01 21:13:00.8784 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpimviyq93/model/ with prefix 28ae5ed6aa6c4cb6
[INFO 26-10-01 21:13:00.8811 +06 kernel.cc:1061] Use fast generic engine