In [20]:
import pandas as pd
import numpy as np
import os
import tensorflow as tf
import tensorflow_decision_forests as tfdf

In [21]:
train_df = pd.read_csv("/Users/aleksandr/Документы/TitanicML/data/train.csv")
test_df = pd.read_csv("/Users/aleksandr/Документы/TitanicML/data/test.csv")

train_df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [22]:
def preprocess(df):
    df = df.copy()
    def normaloize_name(x):
        return " ".join([v.strip(",()[].\"'") for v in x.split(" ")])
    def ticket_number(x):
        return x.split(" ")[-1]
    def ticket_item(x):
        items = x.split(" ")
        if len(items) == 1:
            return "None"
        return "_".join(items[0:-1])
    
    df["Name"] = df["Name"].apply(normaloize_name)
    df["Ticket_number"] = df["Ticket"].apply(ticket_number)
    df["Ticket_item"] = df["Ticket"].apply(ticket_item)
    return df

preprocess_train_df = preprocess(train_df)
preprocess_test_df = preprocess(test_df)

categorical_columns = preprocess_train_df.select_dtypes(
    include=["object", "category"]
).columns

for col in categorical_columns:
    preprocess_train_df[col] = (
        preprocess_train_df[col]
        .fillna("__MISSING__")
        .astype(str)
    )

    preprocess_test_df[col] = (
        preprocess_test_df[col]
        .fillna("__MISSING__")
        .astype(str)
    )

preprocess_train_df.head()

/var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/ipykernel_54728/632754599.py:21: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = preprocess_train_df.select_dtypes(

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Ticket_number,Ticket_item
0,1,0,3,Braund Mr Owen Harris,male,22.0,1,0,A/5 21171,7.2500,__MISSING__,S,21171,A/5
1,2,1,1,Cumings Mrs John Bradley Florence Briggs Thayer,female,38.0,1,0,PC 17599,71.2833,C85,C,17599,PC
2,3,1,3,Heikkinen Miss Laina,female,26.0,0,0,STON/O2. 3101282,7.9250,__MISSING__,S,3101282,STON/O2.
3,4,1,1,Futrelle Mrs Jacques Heath Lily May Peel,female,35.0,1,0,113803,53.1000,C123,S,113803,None
4,5,0,3,Allen Mr William Henry,male,35.0,0,0,373450,8.0500,__MISSING__,S,373450,None

In [23]:
input_features = list(preprocess_train_df.columns)
input_features.remove("Ticket")
input_features.remove("PassengerId")
input_features.remove("Survived")

print(f"Input features: {input_features}")

Input features: ['Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin', 'Embarked', 'Ticket_number', 'Ticket_item']

In [24]:
def tokenize_names(features, labels=None):
    features["Name"] =  tf.strings.split(features["Name"])
    return features, labels

train_ds = tfdf.keras.pd_dataframe_to_tf_dataset(preprocess_train_df,label="Survived").map(tokenize_names)
test_ds = tfdf.keras.pd_dataframe_to_tf_dataset(preprocess_test_df).map(tokenize_names)

In [25]:
model = tfdf.keras.GradientBoostedTreesModel(
    verbose=1, 
    features=[tfdf.keras.FeatureUsage(name=n) for n in input_features],
    exclude_non_specified_features=True,
    min_examples=1,
    categorical_algorithm="RANDOM",
    shrinkage=0.05,
    split_axis="SPARSE_OBLIQUE",
    sparse_oblique_normalization="MIN_MAX",
    sparse_oblique_num_projections_exponent=2.0,
    num_trees=2000,
    random_seed=1234,
    
)
model.fit(train_ds)

self_evaluation = model.make_inspector().evaluation()
print(f"Accuracy: {self_evaluation.accuracy} Loss:{self_evaluation.loss}")

Use /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp4qtbwzwx as temporary training directory
Reading training dataset...
WARNING:tensorflow:6 out of the last 6 calls to <function CoreModel._consumes_training_examples_until_eof at 0x1334dd6c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

[WARNING 26-10-01 20:56:13.7236 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:13.7236 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:13.7236 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
WARNING:tensorflow:6 out of the last 6 calls to <function CoreModel._consumes_training_examples_until_eof at 0x1334dd6c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

Training dataset read in 0:00:00.062806. Found 891 examples.
Training model...
Model trained in 0:00:00.155397
Compiling model...
Model compiled.
WARNING:tensorflow:6 out of the last 10 calls to <function InferenceCoreModel.yggdrasil_model_path_tensor at 0x1345807c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

[INFO 26-10-01 20:56:13.9419 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp4qtbwzwx/model/ with prefix b4f52714223c443f
[INFO 26-10-01 20:56:13.9437 +06 decision_forest.cc:660] Model loaded with 34 root(s), 1818 node(s), and 11 input feature(s).
[INFO 26-10-01 20:56:13.9437 +06 abstract_model.cc:1344] Engine "GradientBoostedTreesGeneric" built
[INFO 26-10-01 20:56:13.9437 +06 kernel.cc:1061] Use fast generic engine
WARNING:tensorflow:6 out of the last 10 calls to <function InferenceCoreModel.yggdrasil_model_path_tensor at 0x1345807c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

Accuracy: 0.79347825050354 Loss:1.0656445026397705

In [26]:
model.summary()

Model: "gradient_boosted_trees_model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
=================================================================
Total params: 1 (1.00 Byte)
Trainable params: 0 (0.00 Byte)
Non-trainable params: 1 (1.00 Byte)
_________________________________________________________________
Type: "GRADIENT_BOOSTED_TREES"
Task: CLASSIFICATION
Label: "__LABEL"

Input Features (11):
	Age
	Cabin
	Embarked
	Fare
	Name
	Parch
	Pclass
	Sex
	SibSp
	Ticket_item
	Ticket_number

No weights

Variable Importance: INV_MEAN_MIN_DEPTH:
    1.           "Sex"  0.588943 ################
    2.           "Age"  0.346745 ######
    3.          "Fare"  0.269876 ###
    4.          "Name"  0.205647 #
    5.         "Cabin"  0.185368
    6.        "Pclass"  0.181872
    7. "Ticket_number"  0.180223
    8.   "Ticket_item"  0.175626
    9.         "Parch"  0.174643
   10.      "Embarked"  0.173688
   11.         "SibSp"  0.171216

Variable Importance: NUM_AS_ROOT:
    1.  "Sex" 29.000000 ################
    2. "Name"  5.000000

Variable Importance: NUM_NODES:
    1.           "Age" 427.000000 ################
    2.          "Fare" 270.000000 ##########
    3.          "Name" 52.000000 #
    4.   "Ticket_item" 34.000000 #
    5.           "Sex" 32.000000 #
    6. "Ticket_number" 22.000000
    7.         "Parch" 17.000000
    8.         "Cabin" 16.000000
    9.        "Pclass" 12.000000
   10.      "Embarked"  5.000000
   11.         "SibSp"  5.000000

Variable Importance: SUM_SCORE:
    1.           "Sex" 429.991580 ################
    2.           "Age" 352.245788 #############
    3.          "Fare" 268.630905 #########
    4.          "Name" 153.238593 #####
    5.        "Pclass" 45.842595 #
    6.         "Cabin" 24.215736
    7. "Ticket_number" 22.497265
    8.   "Ticket_item" 18.571183
    9.         "Parch"  8.449955
   10.      "Embarked"  4.721665
   11.         "SibSp"  0.037139



Loss: BINOMIAL_LOG_LIKELIHOOD
Validation loss value: 1.06564
Number of trees per iteration: 1
Node format: NOT_SET
Number of trees: 34
Total number of nodes: 1818

Number of nodes by tree:
Count: 34 Average: 53.4706 StdDev: 5.51061
Min: 39 Max: 61 Ignored: 0
----------------------------------------------
[ 39, 40) 2   5.88%   5.88% ###
[ 40, 41) 0   0.00%   5.88%
[ 41, 42) 0   0.00%   5.88%
[ 42, 43) 0   0.00%   5.88%
[ 43, 44) 0   0.00%   5.88%
[ 44, 45) 0   0.00%   5.88%
[ 45, 47) 1   2.94%   8.82% #
[ 47, 48) 3   8.82%  17.65% ####
[ 48, 49) 0   0.00%  17.65%
[ 49, 50) 1   2.94%  20.59% #
[ 50, 51) 0   0.00%  20.59%
[ 51, 52) 5  14.71%  35.29% #######
[ 52, 53) 0   0.00%  35.29%
[ 53, 55) 3   8.82%  44.12% ####
[ 55, 56) 5  14.71%  58.82% #######
[ 56, 57) 0   0.00%  58.82%
[ 57, 58) 7  20.59%  79.41% ##########
[ 58, 59) 0   0.00%  79.41%
[ 59, 60) 5  14.71%  94.12% #######
[ 60, 61] 2   5.88% 100.00% ###

Depth by leafs:
Count: 926 Average: 4.85961 StdDev: 0.430668
Min: 2 Max: 5 Ignored: 0
----------------------------------------------
[ 2, 3)   2   0.22%   0.22%
[ 3, 4)  24   2.59%   2.81%
[ 4, 5)  76   8.21%  11.02% #
[ 5, 5] 824  88.98% 100.00% ##########

Number of training obs by leaf:
Count: 926 Average: 29.3369 StdDev: 75.2668
Min: 1 Max: 474 Ignored: 0
----------------------------------------------
[   1,  24) 734  79.27%  79.27% ##########
[  24,  48)  76   8.21%  87.47% #
[  48,  72)  33   3.56%  91.04%
[  72,  95)   8   0.86%  91.90%
[  95, 119)   9   0.97%  92.87%
[ 119, 143)   7   0.76%  93.63%
[ 143, 166)  17   1.84%  95.46%
[ 166, 190)   6   0.65%  96.11%
[ 190, 214)   3   0.32%  96.44%
[ 214, 238)   1   0.11%  96.54%
[ 238, 261)   1   0.11%  96.65%
[ 261, 285)   2   0.22%  96.87%
[ 285, 309)   0   0.00%  96.87%
[ 309, 332)   0   0.00%  96.87%
[ 332, 356)   4   0.43%  97.30%
[ 356, 380)   5   0.54%  97.84%
[ 380, 403)   8   0.86%  98.70%
[ 403, 427)   9   0.97%  99.68%
[ 427, 451)   1   0.11%  99.78%
[ 451, 474]   2   0.22% 100.00%

Attribute in nodes:
	427 : Age [NUMERICAL]
	270 : Fare [NUMERICAL]
	52 : Name [CATEGORICAL_SET]
	34 : Ticket_item [CATEGORICAL]
	32 : Sex [CATEGORICAL]
	22 : Ticket_number [CATEGORICAL]
	17 : Parch [NUMERICAL]
	16 : Cabin [CATEGORICAL]
	12 : Pclass [NUMERICAL]
	5 : SibSp [NUMERICAL]
	5 : Embarked [CATEGORICAL]

Attribute in nodes with depth <= 0:
	29 : Sex [CATEGORICAL]
	5 : Name [CATEGORICAL_SET]

Attribute in nodes with depth <= 1:
	34 : Age [NUMERICAL]
	29 : Sex [CATEGORICAL]
	22 : Fare [NUMERICAL]
	6 : Pclass [NUMERICAL]
	5 : Name [CATEGORICAL_SET]
	5 : Cabin [CATEGORICAL]
	1 : Ticket_number [CATEGORICAL]

Attribute in nodes with depth <= 2:
	105 : Age [NUMERICAL]
	60 : Fare [NUMERICAL]
	30 : Sex [CATEGORICAL]
	13 : Name [CATEGORICAL_SET]
	9 : Cabin [CATEGORICAL]
	7 : Ticket_number [CATEGORICAL]
	6 : Pclass [NUMERICAL]
	3 : Embarked [CATEGORICAL]
	2 : Parch [NUMERICAL]
	1 : Ticket_item [CATEGORICAL]

Attribute in nodes with depth <= 3:
	213 : Age [NUMERICAL]
	139 : Fare [NUMERICAL]
	30 : Sex [CATEGORICAL]
	28 : Name [CATEGORICAL_SET]
	19 : Ticket_number [CATEGORICAL]
	14 : Ticket_item [CATEGORICAL]
	12 : Parch [NUMERICAL]
	12 : Cabin [CATEGORICAL]
	8 : Pclass [NUMERICAL]
	5 : Embarked [CATEGORICAL]

Attribute in nodes with depth <= 5:
	427 : Age [NUMERICAL]
	270 : Fare [NUMERICAL]
	52 : Name [CATEGORICAL_SET]
	34 : Ticket_item [CATEGORICAL]
	32 : Sex [CATEGORICAL]
	22 : Ticket_number [CATEGORICAL]
	17 : Parch [NUMERICAL]
	16 : Cabin [CATEGORICAL]
	12 : Pclass [NUMERICAL]
	5 : SibSp [NUMERICAL]
	5 : Embarked [CATEGORICAL]

Condition type in nodes:
	731 : ObliqueCondition
	126 : ContainsBitmapCondition
	35 : ContainsCondition
Condition type in nodes with depth <= 0:
	34 : ContainsBitmapCondition
Condition type in nodes with depth <= 1:
	62 : ObliqueCondition
	40 : ContainsBitmapCondition
Condition type in nodes with depth <= 2:
	173 : ObliqueCondition
	60 : ContainsBitmapCondition
	3 : ContainsCondition
Condition type in nodes with depth <= 3:
	372 : ObliqueCondition
	93 : ContainsBitmapCondition
	15 : ContainsCondition
Condition type in nodes with depth <= 5:
	731 : ObliqueCondition
	126 : ContainsBitmapCondition
	35 : ContainsCondition

Training logs:
Number of iteration to final model: 34
	Iter:1 train-loss:1.266910 valid-loss:1.364115  train-accuracy:0.624531 valid-accuracy:0.543478
	Iter:2 train-loss:1.215680 valid-loss:1.335395  train-accuracy:0.624531 valid-accuracy:0.543478
	Iter:3 train-loss:1.168280 valid-loss:1.305821  train-accuracy:0.624531 valid-accuracy:0.543478
	Iter:4 train-loss:1.120181 valid-loss:1.274103  train-accuracy:0.624531 valid-accuracy:0.543478
	Iter:5 train-loss:1.079277 valid-loss:1.247148  train-accuracy:0.792240 valid-accuracy:0.706522
	Iter:6 train-loss:1.043451 valid-loss:1.225859  train-accuracy:0.822278 valid-accuracy:0.706522
	Iter:16 train-loss:0.789545 valid-loss:1.118144  train-accuracy:0.909887 valid-accuracy:0.750000
	Iter:26 train-loss:0.651334 valid-loss:1.073267  train-accuracy:0.919900 valid-accuracy:0.782609
	Iter:36 train-loss:0.558133 valid-loss:1.065861  train-accuracy:0.931164 valid-accuracy:0.782609
	Iter:46 train-loss:0.495355 valid-loss:1.076354  train-accuracy:0.937422 valid-accuracy:0.771739
	Iter:56 train-loss:0.451245 valid-loss:1.089698  train-accuracy:0.948686 valid-accuracy:0.728261

In [27]:

def prediction(model, test_df, passenger_ids, threshold=0.5):    
    proba_survive = model.predict(test_ds, verbose=0)[:, 0]
    
    return pd.DataFrame({
        "PassengerId": passenger_ids,
        "Survived": (proba_survive >= threshold).astype(int)
    })

k_prediction = prediction(model, test_ds, test_df["PassengerId"])

def make_submission(k_prediction):
    path = "/Users/aleksandr/Документы/TitanicML/data/gender_submission.csv"
    k_prediction.to_csv(path, index=False)
    print(f"Submission exported to {path}")

make_submission(k_prediction)

Submission exported to /Users/aleksandr/Документы/TitanicML/data/gender_submission.csv

In [28]:
tuner = tfdf.tuner.RandomSearch(num_trials=1000)
tuner.choice("min_examples", [2, 5, 7, 10])
tuner.choice("categorical_algorithm", ["CART", "RANDOM"])

local_search_space = tuner.choice("growing_strategy", ["LOCAL"])
local_search_space.choice("max_depth", [3, 4, 5, 6, 8])

global_search_space = tuner.choice("growing_strategy", ["BEST_FIRST_GLOBAL"], merge=True)
global_search_space.choice("max_num_nodes", [16, 32, 64, 128, 256])

#tuner.choice("use_hessian_gain", [True, False])
tuner.choice("shrinkage", [0.02, 0.05, 0.10, 0.15])
tuner.choice("num_candidate_attributes_ratio", [0.2, 0.5, 0.9, 1.0])


tuner.choice("split_axis", ["AXIS_ALIGNED"])
oblique_space = tuner.choice("split_axis", ["SPARSE_OBLIQUE"], merge=True)
oblique_space.choice("sparse_oblique_normalization",
                     ["NONE", "STANDARD_DEVIATION", "MIN_MAX"])
oblique_space.choice("sparse_oblique_weights", ["BINARY", "CONTINUOUS"])
oblique_space.choice("sparse_oblique_num_projections_exponent", [1.0, 1.5])

# Tune the model. Notice the `tuner=tuner`.
tuned_model = tfdf.keras.GradientBoostedTreesModel(tuner=tuner)
tuned_model.fit(train_ds, verbose=0)

tuned_self_evaluation = tuned_model.make_inspector().evaluation()
print(f"Accuracy: {tuned_self_evaluation.accuracy} Loss:{tuned_self_evaluation.loss}")

Use /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpfmdlcdzg as temporary training directory

[WARNING 26-10-01 20:56:14.0525 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:14.0525 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:14.0525 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

Accuracy: 0.8493150472640991 Loss:0.6777517199516296

[INFO 26-10-01 20:56:30.3918 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpfmdlcdzg/model/ with prefix 726ff1eedc094913
[INFO 26-10-01 20:56:30.4038 +06 decision_forest.cc:660] Model loaded with 84 root(s), 10236 node(s), and 13 input feature(s).
[INFO 26-10-01 20:56:30.4038 +06 abstract_model.cc:1344] Engine "GradientBoostedTreesGeneric" built
[INFO 26-10-01 20:56:30.4038 +06 kernel.cc:1061] Use fast generic engine

In [29]:
predictions = None
num_predictions = 0

for i in range(100):
    print(f"i:{i}")
    # Possible models: GradientBoostedTreesModel or RandomForestModel
    model = tfdf.keras.GradientBoostedTreesModel(
        verbose=0, # Very few logs
        features=[tfdf.keras.FeatureUsage(name=n) for n in input_features],
        exclude_non_specified_features=True, # Only use the features in "features"

        #min_examples=1,
        #categorical_algorithm="RANDOM",
        ##max_depth=4,
        #shrinkage=0.05,
        ##num_candidate_attributes_ratio=0.2,
        #split_axis="SPARSE_OBLIQUE",
        #sparse_oblique_normalization="MIN_MAX",
        #sparse_oblique_num_projections_exponent=2.0,
        #num_trees=2000,
        ##validation_ratio=0.0,
        random_seed=i,
        honest=True,
    )
    model.fit(train_ds)
    
    sub_predictions = model.predict(test_ds, verbose=0)[:,0]
    if predictions is None:
        predictions = sub_predictions
    else:
        predictions += sub_predictions
    num_predictions += 1

predictions/=num_predictions

kaggle_predictions = pd.DataFrame({
        "PassengerId": test_df["PassengerId"],
        "Survived": (predictions >= 0.5).astype(int)
    })

make_submission(kaggle_predictions)

[WARNING 26-10-01 20:56:30.4785 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:30.4786 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:30.4786 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:0

[INFO 26-10-01 20:56:30.6360 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpjsvznblu/model/ with prefix 12581b04e84e4426
[INFO 26-10-01 20:56:30.6372 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:30.7283 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:30.7283 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:30.7283 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:1

[INFO 26-10-01 20:56:30.8737 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmptyglji34/model/ with prefix e167ab9499724014
[INFO 26-10-01 20:56:30.8751 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:30.9651 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:30.9651 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:30.9651 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:2

[INFO 26-10-01 20:56:31.1182 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpt4baf20h/model/ with prefix 1f75822c282d4e95
[INFO 26-10-01 20:56:31.1199 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:31.2241 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:31.2241 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:31.2241 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:3

[INFO 26-10-01 20:56:31.4034 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpypi0b01a/model/ with prefix aa8a46d069b94d6b
[INFO 26-10-01 20:56:31.4056 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:31.4962 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:31.4963 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:31.4963 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:4

[INFO 26-10-01 20:56:31.6347 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpd4e39gdv/model/ with prefix 9db79de6c6a74715
[INFO 26-10-01 20:56:31.6361 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:31.7271 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:31.7271 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:31.7271 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:5

[INFO 26-10-01 20:56:31.8579 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmppqdfzssg/model/ with prefix c25759d1ca7a4b34
[INFO 26-10-01 20:56:31.8588 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:31.9601 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:31.9601 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:31.9601 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:6

[INFO 26-10-01 20:56:32.1760 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpaye437cn/model/ with prefix e3a70f0b16414c4b
[INFO 26-10-01 20:56:32.1793 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:32.2665 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:32.2665 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:32.2665 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:7

[INFO 26-10-01 20:56:32.4053 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpm5mzmvoe/model/ with prefix f827a68df70f4f8f
[INFO 26-10-01 20:56:32.4064 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:32.4967 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:32.4967 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:32.4967 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:8

[INFO 26-10-01 20:56:32.6775 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpgncyh19n/model/ with prefix 1ccc4ffe9afd4a85
[INFO 26-10-01 20:56:32.6796 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:32.7696 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:32.7696 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:32.7696 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:9

[INFO 26-10-01 20:56:32.9188 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpyzb_gddp/model/ with prefix 94b755241578497f
[INFO 26-10-01 20:56:32.9203 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:33.0096 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:33.0096 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:33.0096 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:10

[INFO 26-10-01 20:56:33.1877 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp_6v0qpah/model/ with prefix f3154ca312674502
[INFO 26-10-01 20:56:33.1901 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:33.2944 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:33.2944 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:33.2944 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:11

[INFO 26-10-01 20:56:33.5094 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp296v0k__/model/ with prefix 66a723cf797d4872
[INFO 26-10-01 20:56:33.5125 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:33.5998 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:33.5999 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:33.5999 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:12

[INFO 26-10-01 20:56:33.7433 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmplbonxiqo/model/ with prefix e768b298f0864fe2
[INFO 26-10-01 20:56:33.7446 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:33.9143 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:33.9143 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:33.9143 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:13

[INFO 26-10-01 20:56:34.1200 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpbmkanke8/model/ with prefix 6471a0e637a24147
[INFO 26-10-01 20:56:34.1226 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:34.2116 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:34.2116 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:34.2116 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:14

[INFO 26-10-01 20:56:34.3785 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp1qoglmsa/model/ with prefix 47b5366b0b1b488e
[INFO 26-10-01 20:56:34.3806 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:34.4719 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:34.4719 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:34.4719 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:15

[INFO 26-10-01 20:56:34.6140 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpsqxhfjq3/model/ with prefix 9a369043a18248cc
[INFO 26-10-01 20:56:34.6153 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:34.7244 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:34.7244 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:34.7244 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:16

[INFO 26-10-01 20:56:34.8815 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpg51ft7q0/model/ with prefix 8b637d64420b4598
[INFO 26-10-01 20:56:34.8830 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:34.9743 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:34.9743 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:34.9744 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:17

[INFO 26-10-01 20:56:35.1700 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpbroy03wx/model/ with prefix cbe96e3d77ca41a1
[INFO 26-10-01 20:56:35.1730 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:35.2635 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:35.2635 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:35.2635 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:18

[INFO 26-10-01 20:56:35.4144 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpf10wozlu/model/ with prefix 9a87a9c3b9114ce1
[INFO 26-10-01 20:56:35.4160 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:35.5043 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:35.5043 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:35.5043 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:19

[INFO 26-10-01 20:56:35.7447 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmphs1_0hw5/model/ with prefix 583bd7b5f9944779
[INFO 26-10-01 20:56:35.7484 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:35.8343 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:35.8343 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:35.8343 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:20

[INFO 26-10-01 20:56:36.0289 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp6gsn1g4o/model/ with prefix 23412d96b88349d9
[INFO 26-10-01 20:56:36.0316 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:36.1201 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:36.1201 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:36.1201 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:21

[INFO 26-10-01 20:56:36.2888 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpt7k66s3p/model/ with prefix 082d3dce9e6945b4
[INFO 26-10-01 20:56:36.2908 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:36.3799 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:36.3799 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:36.3799 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:22

[INFO 26-10-01 20:56:36.5441 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp7_qornbg/model/ with prefix 7540d53804fb4a32
[INFO 26-10-01 20:56:36.5461 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:36.6519 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:36.6519 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:36.6519 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:23

[INFO 26-10-01 20:56:36.8144 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpkxmyyc3j/model/ with prefix 4cca540b58304b97
[INFO 26-10-01 20:56:36.8162 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:36.9065 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:36.9065 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:36.9065 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:24

[INFO 26-10-01 20:56:37.0515 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpa4r_bs7a/model/ with prefix aa5d0f677023455d
[INFO 26-10-01 20:56:37.0529 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:37.1416 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:37.1416 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:37.1416 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:25

[INFO 26-10-01 20:56:37.3133 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpu99livw4/model/ with prefix 18c8407f20ed4b9c
[INFO 26-10-01 20:56:37.3154 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:37.4057 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:37.4058 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:37.4058 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:26

[INFO 26-10-01 20:56:37.6032 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpkfvig0bl/model/ with prefix c04462da744144b5
[INFO 26-10-01 20:56:37.6058 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:37.6946 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:37.6946 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:37.6946 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:27

[INFO 26-10-01 20:56:37.8824 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp4r16o24w/model/ with prefix efbb80f49f404dbb
[INFO 26-10-01 20:56:37.8852 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:37.9751 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:37.9751 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:37.9751 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:28

[INFO 26-10-01 20:56:38.1117 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmplnq440fv/model/ with prefix cc77bfa5d4324630
[INFO 26-10-01 20:56:38.1128 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:38.2027 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:38.2027 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:38.2027 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:29

[INFO 26-10-01 20:56:38.3498 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp0_d_sssv/model/ with prefix 03c5b679f48e4875
[INFO 26-10-01 20:56:38.3514 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:38.4557 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:38.4557 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:38.4557 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:30

[INFO 26-10-01 20:56:38.6516 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp7gol4tri/model/ with prefix c11f59aeba8c49d2
[INFO 26-10-01 20:56:38.6544 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:38.7439 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:38.7439 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:38.7439 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:31

[INFO 26-10-01 20:56:38.9512 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp131mkvaa/model/ with prefix 6a8a2ff932f74e91
[INFO 26-10-01 20:56:38.9548 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:39.0436 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:39.0436 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:39.0436 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:32

[INFO 26-10-01 20:56:39.3234 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmptw40f9ma/model/ with prefix c5927de7da59426d
[INFO 26-10-01 20:56:39.3258 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:39.4133 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:39.4133 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:39.4133 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:33

[INFO 26-10-01 20:56:39.6072 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpu842faca/model/ with prefix 31a9eebcda4845c6
[INFO 26-10-01 20:56:39.6092 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:39.6989 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:39.6989 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:39.6989 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:34

[INFO 26-10-01 20:56:39.8520 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpdhas7own/model/ with prefix aa4b39268ec7433b
[INFO 26-10-01 20:56:39.8537 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:39.9451 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:39.9451 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:39.9451 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:35

[INFO 26-10-01 20:56:40.1179 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp11s342tz/model/ with prefix fa26882a70c14bbd
[INFO 26-10-01 20:56:40.1202 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:40.2127 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:40.2127 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:40.2127 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:36

[INFO 26-10-01 20:56:40.3490 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp62hl91p1/model/ with prefix cb30f28400774069
[INFO 26-10-01 20:56:40.3501 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:40.4561 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:40.4561 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:40.4561 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:37

[INFO 26-10-01 20:56:40.6360 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp9hdpbz13/model/ with prefix 98fa663d64884b27
[INFO 26-10-01 20:56:40.6385 +06 abstract_model.cc:1344] Engine "GradientBoostedTreesQuickScorerExtended" built
[INFO 26-10-01 20:56:40.6385 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:40.7304 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:40.7304 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:40.7304 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:38

[INFO 26-10-01 20:56:41.0779 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpia3zv2vm/model/ with prefix d5da7d726fa744f6
[INFO 26-10-01 20:56:41.0847 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:41.1743 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:41.1743 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:41.1743 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:39

[INFO 26-10-01 20:56:41.4104 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpmy1euou9/model/ with prefix 4813a902d30b4d14
[INFO 26-10-01 20:56:41.4163 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:41.5044 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:41.5044 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:41.5044 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:40

[INFO 26-10-01 20:56:41.6726 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmptc8cfs39/model/ with prefix 90e4f43531754ece
[INFO 26-10-01 20:56:41.6746 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:41.7649 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:41.7649 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:41.7649 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:41

[INFO 26-10-01 20:56:41.9451 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp3b7ojmyi/model/ with prefix 8f3fe461cf7a443f
[INFO 26-10-01 20:56:41.9474 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:42.0388 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:42.0388 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:42.0388 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:42

[INFO 26-10-01 20:56:42.1716 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmplak1ru2z/model/ with prefix 9d5f9fb4573f40ea
[INFO 26-10-01 20:56:42.1725 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:42.2731 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:42.2731 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:42.2731 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:43

[INFO 26-10-01 20:56:42.5041 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp5sgt8x7h/model/ with prefix 5e6295b6e16048ff
[INFO 26-10-01 20:56:42.5077 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:42.5943 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:42.5943 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:42.5943 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:44

[INFO 26-10-01 20:56:42.7248 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpq28y_vds/model/ with prefix c720af88947b45f2
[INFO 26-10-01 20:56:42.7258 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:42.8133 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:42.8134 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:42.8134 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:45

[INFO 26-10-01 20:56:42.9532 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpr4bq6ct7/model/ with prefix c6c17b9748214fc7
[INFO 26-10-01 20:56:42.9544 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:43.0576 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:43.0576 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:43.0576 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:46

[INFO 26-10-01 20:56:43.2104 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpbcbk55ux/model/ with prefix 4659030a251c4b5c
[INFO 26-10-01 20:56:43.2119 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:43.3010 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:43.3011 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:43.3011 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:47

[INFO 26-10-01 20:56:43.5204 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp8lx__axu/model/ with prefix d1bf29aa9bc54188
[INFO 26-10-01 20:56:43.5238 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:43.6102 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:43.6102 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:43.6102 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:48

[INFO 26-10-01 20:56:43.7429 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpu48clb0i/model/ with prefix f5828b173952455f
[INFO 26-10-01 20:56:43.7439 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:43.8408 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:43.8408 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:43.8409 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:49

[INFO 26-10-01 20:56:44.0380 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpv_upttmz/model/ with prefix 5474b8ff606b4c2a
[INFO 26-10-01 20:56:44.0405 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:44.1291 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:44.1291 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:44.1291 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:50

[INFO 26-10-01 20:56:44.3406 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpcd8dudkj/model/ with prefix a917a050686444b0
[INFO 26-10-01 20:56:44.3445 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:44.4329 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:44.4329 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:44.4329 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:51

[INFO 26-10-01 20:56:44.6302 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpvi6tdhuf/model/ with prefix 51cc8314cd134b06
[INFO 26-10-01 20:56:44.6330 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:44.7227 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:44.7228 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:44.7228 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:52

[INFO 26-10-01 20:56:44.8870 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpp8sep6eg/model/ with prefix 4686f8bce1d94781
[INFO 26-10-01 20:56:44.8886 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:44.9772 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:44.9772 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:44.9772 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:53

[INFO 26-10-01 20:56:45.1492 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpur_qoirt/model/ with prefix 4b0197d475274322
[INFO 26-10-01 20:56:45.1513 +06 kernel.cc:1061] Use fast generic engine

i:54

[WARNING 26-10-01 20:56:45.3587 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:45.3587 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:45.3587 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
[INFO 26-10-01 20:56:45.4974 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpw5rvbb_n/model/ with prefix c0dc3861eab14d25
[INFO 26-10-01 20:56:45.4984 +06 kernel.cc:1061] Use fast generic engine

i:55

[WARNING 26-10-01 20:56:45.5887 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:45.5888 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:45.5888 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
[INFO 26-10-01 20:56:45.7491 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpflzba35v/model/ with prefix 4e8415a29f7b4730
[INFO 26-10-01 20:56:45.7511 +06 kernel.cc:1061] Use fast generic engine

i:56

[WARNING 26-10-01 20:56:45.8438 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:45.8438 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:45.8438 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
[INFO 26-10-01 20:56:46.0532 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp75rye1_q/model/ with prefix 01966518ae2a4c1d
[INFO 26-10-01 20:56:46.0573 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:46.1480 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:46.1480 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:46.1480 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:57

[INFO 26-10-01 20:56:46.3156 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpu0u5wjwr/model/ with prefix 3d7d0243fc324e5c
[INFO 26-10-01 20:56:46.3178 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:46.4258 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:46.4258 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:46.4258 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:58

[INFO 26-10-01 20:56:46.6244 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpkjjsah1n/model/ with prefix 8d300e6f569a4c0f
[INFO 26-10-01 20:56:46.6275 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:46.7188 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:46.7189 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:46.7189 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:59

[INFO 26-10-01 20:56:46.9520 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp8kmoe_zt/model/ with prefix 9686c31623ee4e6b
[INFO 26-10-01 20:56:46.9559 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:47.0447 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:47.0447 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:47.0447 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:60

[INFO 26-10-01 20:56:47.2035 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpbg4fgprv/model/ with prefix 19516671256c4ac4
[INFO 26-10-01 20:56:47.2053 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:47.2952 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:47.2952 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:47.2952 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:61

[INFO 26-10-01 20:56:47.4687 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpp43tn7cz/model/ with prefix e62d0358804a42a4
[INFO 26-10-01 20:56:47.4707 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:47.5608 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:47.5608 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:47.5608 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:62

[INFO 26-10-01 20:56:47.7349 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp6oe1gc5c/model/ with prefix a1ce821d29e040c1
[INFO 26-10-01 20:56:47.7371 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:47.8277 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:47.8277 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:47.8277 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:63

[INFO 26-10-01 20:56:47.9759 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp819ee5nj/model/ with prefix 7f01876963e64abc
[INFO 26-10-01 20:56:47.9770 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:48.0682 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:48.0683 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:48.0683 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:64

[INFO 26-10-01 20:56:48.2312 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpsvxi8ln7/model/ with prefix 5b0c38ed3fb54055
[INFO 26-10-01 20:56:48.2330 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:48.3230 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:48.3230 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:48.3230 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:65

[INFO 26-10-01 20:56:48.4741 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpeswla88f/model/ with prefix 7296a1aa238744b9
[INFO 26-10-01 20:56:48.4756 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:48.5648 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:48.5649 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:48.5649 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:66

[INFO 26-10-01 20:56:48.7132 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpadl188pd/model/ with prefix 620295cb274f456b
[INFO 26-10-01 20:56:48.7147 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:48.8038 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:48.8038 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:48.8038 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:67

[INFO 26-10-01 20:56:48.9925 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpswxb59o3/model/ with prefix 58b5aa76985a4749
[INFO 26-10-01 20:56:48.9951 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:49.0844 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:49.0844 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:49.0844 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:68

[INFO 26-10-01 20:56:49.2964 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpgdhtccgk/model/ with prefix 686b54603a094e1e
[INFO 26-10-01 20:56:49.2994 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:49.3871 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:49.3872 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:49.3872 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:69

[INFO 26-10-01 20:56:49.5323 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp53idb214/model/ with prefix 620084dbb2874d5c
[INFO 26-10-01 20:56:49.5336 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:49.6230 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:49.6230 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:49.6230 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:70

[INFO 26-10-01 20:56:49.8474 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpcrqhvv9u/model/ with prefix fd13ac3b584d4d29
[INFO 26-10-01 20:56:49.8509 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:49.9384 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:49.9384 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:49.9384 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:71

[INFO 26-10-01 20:56:50.0979 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpyoyd9s5s/model/ with prefix be22b5b3985b4a51
[INFO 26-10-01 20:56:50.0996 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:50.1896 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:50.1897 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:50.1897 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:72

[INFO 26-10-01 20:56:50.3593 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpqvi4c5fh/model/ with prefix 9bb154884ed94576
[INFO 26-10-01 20:56:50.3613 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:50.4505 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:50.4505 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:50.4505 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:73

[INFO 26-10-01 20:56:50.6148 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpy24rp5gn/model/ with prefix d8643ed058a7417c
[INFO 26-10-01 20:56:50.6163 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:50.7051 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:50.7051 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:50.7051 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:74

[INFO 26-10-01 20:56:50.9865 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp5y9jr134/model/ with prefix 84c7089b6ab34249
[INFO 26-10-01 20:56:50.9915 +06 abstract_model.cc:1344] Engine "GradientBoostedTreesQuickScorerExtended" built
[INFO 26-10-01 20:56:50.9915 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:51.0787 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:51.0787 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:51.0787 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:75

[INFO 26-10-01 20:56:51.2807 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp63cxxtdd/model/ with prefix 194279156baf4b57
[INFO 26-10-01 20:56:51.2837 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:51.3731 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:51.3731 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:51.3731 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:76

[INFO 26-10-01 20:56:51.5117 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpqwca0nn1/model/ with prefix 173d4cb021624df2
[INFO 26-10-01 20:56:51.5127 +06 kernel.cc:1061] Use fast generic engine

i:77

[WARNING 26-10-01 20:56:51.7391 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:51.7391 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:51.7391 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
[INFO 26-10-01 20:56:51.8888 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp0zk3wb3l/model/ with prefix c512648620fb4298
[INFO 26-10-01 20:56:51.8902 +06 kernel.cc:1061] Use fast generic engine

i:78

[WARNING 26-10-01 20:56:52.0046 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:52.0046 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:52.0046 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
[INFO 26-10-01 20:56:52.1950 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpbrs7gov5/model/ with prefix d218ee8ba18843a4
[INFO 26-10-01 20:56:52.1975 +06 kernel.cc:1061] Use fast generic engine

i:79

[WARNING 26-10-01 20:56:52.2902 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:52.2903 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:52.2903 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
[INFO 26-10-01 20:56:52.4616 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpvpuqpq36/model/ with prefix d5e8a4055f9f4015
[INFO 26-10-01 20:56:52.4638 +06 kernel.cc:1061] Use fast generic engine

i:80

[WARNING 26-10-01 20:56:52.5567 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:52.5567 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:52.5567 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
[INFO 26-10-01 20:56:52.7008 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpc4l26ctv/model/ with prefix 490c76cb4a29435a
[INFO 26-10-01 20:56:52.7020 +06 kernel.cc:1061] Use fast generic engine

i:81

[WARNING 26-10-01 20:56:52.7930 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:52.7930 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:52.7930 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
[INFO 26-10-01 20:56:52.9425 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp8zw5g07c/model/ with prefix 3031124925e84977
[INFO 26-10-01 20:56:52.9440 +06 kernel.cc:1061] Use fast generic engine

i:82

[WARNING 26-10-01 20:56:53.0359 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:53.0359 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:53.0360 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
[INFO 26-10-01 20:56:53.2012 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpn4w64x8b/model/ with prefix bba0a2b56c564c6e
[INFO 26-10-01 20:56:53.2030 +06 kernel.cc:1061] Use fast generic engine

i:83

[WARNING 26-10-01 20:56:53.2962 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:53.2962 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:53.2962 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
[INFO 26-10-01 20:56:53.4551 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpchyysc71/model/ with prefix 8ba25da498b246a9
[INFO 26-10-01 20:56:53.4568 +06 kernel.cc:1061] Use fast generic engine

i:84

[WARNING 26-10-01 20:56:53.5666 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:53.5666 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:53.5666 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
[INFO 26-10-01 20:56:53.7692 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmptfzwmv28/model/ with prefix 447ae78a816d4588
[INFO 26-10-01 20:56:53.7721 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:53.8653 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:53.8653 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:53.8653 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:85

[INFO 26-10-01 20:56:54.0009 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmprd13gmfl/model/ with prefix 2cec0f1e69a542c1
[INFO 26-10-01 20:56:54.0020 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:54.0928 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:54.0928 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:54.0928 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:86

[INFO 26-10-01 20:56:54.3450 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp1p83k799/model/ with prefix 9f08c90c47f94d96
[INFO 26-10-01 20:56:54.3489 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:54.4350 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:54.4350 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:54.4350 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:87

[INFO 26-10-01 20:56:54.6373 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp9v_xiw4f/model/ with prefix c3cd3be1002546a1
[INFO 26-10-01 20:56:54.6401 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:54.7293 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:54.7293 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:54.7293 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:88

[INFO 26-10-01 20:56:54.9062 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmp56_jlv43/model/ with prefix b53863ccf7e1473a
[INFO 26-10-01 20:56:54.9084 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:55.0135 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:55.0135 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:55.0135 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:89

[INFO 26-10-01 20:56:55.1866 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpo6zu0m_g/model/ with prefix 77b8a17c63fc4058
[INFO 26-10-01 20:56:55.1887 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:55.2796 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:55.2796 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:55.2796 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:90

[INFO 26-10-01 20:56:55.4685 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpusex_0s6/model/ with prefix 15a7c20d284849f9
[INFO 26-10-01 20:56:55.4711 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:55.5608 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:55.5609 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:55.5609 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:91

[INFO 26-10-01 20:56:55.7636 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpozp4yifg/model/ with prefix 9757152a08684f01
[INFO 26-10-01 20:56:55.7666 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:55.8567 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:55.8568 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:55.8568 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:92

[INFO 26-10-01 20:56:56.0761 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpn5xd1xuc/model/ with prefix 9d5ea2cb9986496c
[INFO 26-10-01 20:56:56.0791 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:56.1670 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:56.1670 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:56.1670 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:93

[INFO 26-10-01 20:56:56.4000 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpakitm2ku/model/ with prefix 8849d4e544564930
[INFO 26-10-01 20:56:56.4033 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:56.4893 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:56.4893 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:56.4893 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:94

[INFO 26-10-01 20:56:56.6487 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpg7nt9cv2/model/ with prefix 8f3a591dda0f465a
[INFO 26-10-01 20:56:56.6503 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:56.7399 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:56.7399 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:56.7399 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:95

[INFO 26-10-01 20:56:56.8801 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpd4049_z8/model/ with prefix baa6e038fa334260
[INFO 26-10-01 20:56:56.8812 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:56.9704 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:56.9704 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:56.9704 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:96

[INFO 26-10-01 20:56:57.1492 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmprpkzg69m/model/ with prefix 8a0dfb57882b4a3c
[INFO 26-10-01 20:56:57.1516 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:57.2421 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:57.2421 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:57.2421 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:97

[INFO 26-10-01 20:56:57.4309 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpj3bw7ue1/model/ with prefix e2c68cf2a0df4e1e
[INFO 26-10-01 20:56:57.4332 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:57.5388 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:57.5388 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:57.5388 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:98

[INFO 26-10-01 20:56:57.7204 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpngrqf6yh/model/ with prefix b095cb7b878c449f
[INFO 26-10-01 20:56:57.7227 +06 kernel.cc:1061] Use fast generic engine
[WARNING 26-10-01 20:56:57.8120 +06 gradient_boosted_trees.cc:1886] "goss_alpha" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:57.8121 +06 gradient_boosted_trees.cc:1897] "goss_beta" set but "sampling_method" not equal to "GOSS".
[WARNING 26-10-01 20:56:57.8121 +06 gradient_boosted_trees.cc:1911] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".

i:99
Submission exported to /Users/aleksandr/Документы/TitanicML/data/gender_submission.csv

[INFO 26-10-01 20:56:58.0084 +06 kernel.cc:1233] Loading model from path /var/folders/3z/c5bxtqgx0yj70y6vbqnfwxtw0000gn/T/tmpbncxikpq/model/ with prefix 4af2ca904a274554
[INFO 26-10-01 20:56:58.0111 +06 kernel.cc:1061] Use fast generic engine